apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
   host: YW1xcHM6Ly9VU0VSOlBBU1NASE9TVC9WSE9TVA==

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
  namespace: keda
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: keda
spec:
  scaleTargetRef:
    name: rabbitmq-receiver
  pollingInterval: 20 #Interval to check each trigger on.
  cooldownPeriod: 120 #Cooldown period between scale up and down.
  maxReplicaCount: 20 #Maximum number of replicas.
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: hello
      mode: QueueLength
      value: "5"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn

