apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-prductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-producer
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      containers:
      - name: rabbitmq-producer
        image: tazimtaz/producer_mq:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-producer-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq-producer
  ports:
  - port: 8000