name: docker-build-push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: ubuntu-latest

    steps:
      - name: build
        uses: actions/checkout@v2
      
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version number
        id: vars
        run: echo "{{ github.event.head_commit.id }}"

      - name: Build and push the latest producer image
        working-directory: ./producer
        run: |
          docker build -t tazimtaz/producer_mq:latest .
          docker push tazimtaz/producer_mq:latest
      - name: Build and push the latest recevier image
        working-directory: ./recevier
        run: |
          docker build -t tazimtaz/recevier_mq:latest .
          docker push tazimtaz/recevier_mq:latest